# We need to specify static IP address, because this IP address has to be part
# of private network configuration, see: libvirt__dhcp_bootp_server: network[:bootp_server]
ip_addr = '192.168.111.5'
ip_prefix = '24'

Vagrant.configure("2") do |config|
  config.vm.hostname = 'pxe-server'
  config.vm.box = 'centos/7'
  config.vm.define 'pxe-server'

  config.ssh.forward_x11 = true

  config.vm.network "private_network",
    ip: ip_addr,
    auto_config: false,
    libvirt__dhcp_bootp_file: 'pxelinux.0',
    libvirt__dhcp_bootp_server: ip_addr

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "../vagrant/vagrant_pxe_server.yml"
    ansible.groups = {
      "pxe-servers" => [
        "pxe-server"
      ]
    }
    ansible.extra_vars = {
      "pxe_server_ip_addr" => ip_addr + '/' + ip_prefix
    }
  end
end